In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# config.py

DATABASE_CONFIG = {
    'host': 'localhost',
    'port': 3310,
    'user': 'root',
    'password': 'root',
    'database': 'retail_db'
}

CSV_FILES = {
    'customers': 'data/customers.csv',
    'departments': 'data/departments.csv',
    'categories': 'data/categories.csv',
    'products': 'data/products.csv',
    'orders': 'data/orders.csv',
    'order_items': 'data/order_items.csv'
}

LOG_FILE = 'logs/pipeline.log'

In [ ]:
# leo un dataframe para validar el metodo
customers_df = pd.read_csv(CSV_FILES['customers'])
customers_df.head()

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725

In [11]:
# El primer isnull te regresa si existe elementos nullos
customers_df[['customer_fname', 'customer_lname', 'customer_email']].isnull()

       customer_fname  customer_lname  customer_email
0               False           False           False
1               False           False           False
2               False           False           False
3               False           False           False
4               False           False           False
...               ...             ...             ...
12430           False           False           False
12431           False           False           False
12432           False           False           False
12433           False           False           False
12434           False           False           False

[12435 rows x 3 columns]

In [12]:
# El primer any te asegurra que no si existe en cada columna un valor true
customers_df[['customer_fname', 'customer_lname', 'customer_email']].isnull().any()

customer_fname    False
customer_lname    False
customer_email    False
dtype: bool

In [ ]:
# El segundo any te asegurra que no si existe en cada una de los 3 elementos seleccionados
customers_df[['customer_fname', 'customer_lname', 'customer_email']].isnull().any().any()

np.False_

In [ ]:
# Podriamos valdiarlo cambiando un elemento del archivo csv

In [14]:
if customers_df[['customer_fname', 'customer_lname', 'customer_email']].isnull().any().any(): #primer any a nivel de columna, el segundo es las 3 col
        print('Se ha encontrado un valor nulo en el dataframe')

In [ ]:
# Te evalua si es un valor duplicado, los primeros elementos te devuelve true y luego false
# importante el duplicated evalua la combinacion de columnas, por eso no es necesario dos any o mas
customers_df['customer_city'].duplicated()#.any()

np.True_